name: auto_merge

on:
  workflow_dispatch:
  schedule:
    - cron: 10/10 * * * *


jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master
        fetch-depth: 0
        lfs: true
        token: ${{ secrets.PAT}}

    - name: Set git identity
      run : |
        git config --global user.email "qwq233@qwq2333.top"
        git config --global user.name "github-actions[bot]"
    - name: Load upstream commits
      run:
        git pull https://github.com/ferredoxin/QNotified.git master --ff
    - name: Apply commit changes
      run: |
        if [ -f ./.git/MERGE_MSG ]; then
        mkdir ./tmp && cp ./.git/MERGE_MSG ./tmp/message
        sed -i "1c [bot] AutoMerging: merge all upstream's changes:" ./tmp/message
        sed -i '/^\#.*/d' ./tmp/message
        git commit --file="./tmp/message"
        else
        echo "There is no merge commits."
        fi
    - name: Push Commits
      env:
        DOWNSTREAM_BRANCH: master
        TZ: Asia/Shanghai
      run: git push origin $DOWNSTREAM_BRANCH
